import "tailwindcss/tailwind.css";
import Providers from "./Providers";

export const metadata = {
  title: "Flage World",
  description: "Generated by Next.js and Talwind and tsx",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
